# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KM onGoing
email: kmongoing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  한의학 고문헌 연구 집단
baseurl: "/document" # the subpath of your site, e.g. /blog
url: "http://kmongoing.github.io" # the base hostname & protocol for your site
github: [Repository metadata] # https://help.github.com/articles/using-jekyll-with-pages/

# Author
github_username:  kmongoing

# Build settings
permalink: /:categories/:title
host: 0.0.0.0
port: 8384
timezone: Asia/Seoul
markdown: kramdown
# markdown: redcarpet
# redcarpet:
#   extensions: [strikethrough, tables]
sass:
  sass_dir: public/css
  style: :compressed
#theme: "brume (https://github.com/aigarsdz/brume)"

# Front Matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
